"""add notes to trip location

Revision ID: 2dd30e162947
Revises: 
Create Date: 2026-04-28 15:26:53.505294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd30e162947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_location', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
