"""add cascade delete

Revision ID: e8c45e0a39d3
Revises: 2dd30e162947
Create Date: 2026-04-29 18:54:03.003102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c45e0a39d3'
down_revision = '2dd30e162947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('photo_location_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trip_location', ['location_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('trip_location', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('trip_location_trip_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trip', ['trip_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trip_location_trip_id_fkey'), 'trip', ['trip_id'], ['id'])

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('photo_location_id_fkey'), 'trip_location', ['location_id'], ['id'])

    # ### end Alembic commands ###
